import type { Category } from "../types";

export const defaultCategories: Category[] = [
	{
		id: "1",
		name: "Food & Dining",
		type: "expense",
		icon: "Utensils",
		lifestyleType: "need",
	},
	{
		id: "2",
		name: "Groceries",
		type: "expense",
		icon: "Utensils",
		lifestyleType: "need",
		mainCategoryId: "1",
	},
	{
		id: "3",
		name: "Transportation",
		type: "expense",
		icon: "Car",
		lifestyleType: "need",
	},
	{
		id: "4",
		name: "Fuel",
		type: "expense",
		icon: "Car",
		lifestyleType: "need",
		mainCategoryId: "3",
	},
	{
		id: "5",
		name: "Housing",
		type: "expense",
		icon: "Home",
		lifestyleType: "need",
	},
	{
		id: "6",
		name: "Rent",
		type: "expense",
		icon: "Home",
		lifestyleType: "need",
		mainCategoryId: "5",
	},
	{
		id: "7",
		name: "Entertainment",
		type: "expense",
		icon: "Film",
		lifestyleType: "want",
	},
	{
		id: "8",
		name: "Movies",
		type: "expense",
		icon: "Film",
		lifestyleType: "want",
		mainCategoryId: "7",
	},
	{
		id: "9",
		name: "Shopping",
		type: "expense",
		icon: "ShoppingBag",
		lifestyleType: "want",
	},
	{
		id: "10",
		name: "Clothing",
		type: "expense",
		icon: "ShoppingBag",
		lifestyleType: "want",
		mainCategoryId: "9",
	},
	{
		id: "11",
		name: "Utilities",
		type: "expense",
		icon: "Zap",
		lifestyleType: "need",
	},
	{
		id: "12",
		name: "Electricity",
		type: "expense",
		icon: "Zap",
		lifestyleType: "need",
		mainCategoryId: "11",
	},
	{
		id: "13",
		name: "Health",
		type: "expense",
		icon: "HeartPulse",
		lifestyleType: "need",
	},
	{
		id: "14",
		name: "Insurance",
		type: "expense",
		icon: "HeartPulse",
		lifestyleType: "need",
		mainCategoryId: "13",
	},
	{
		id: "15",
		name: "Other",
		type: "expense",
		icon: "MoreHorizontal",
		lifestyleType: "want",
	},
	{
		id: "16",
		name: "Misc",
		type: "expense",
		icon: "MoreHorizontal",
		lifestyleType: "want",
		mainCategoryId: "15",
	},
	{
		id: "17",
		name: "Salary",
		type: "income",
		icon: "Briefcase",
		lifestyleType: "income",
	},
	{
		id: "18",
		name: "Freelance",
		type: "income",
		icon: "Laptop",
		lifestyleType: "income",
	},
	{
		id: "19",
		name: "Investments",
		type: "income",
		icon: "TrendingUp",
		lifestyleType: "income",
	},
	{
		id: "20",
		name: "Gifts",
		type: "income",
		icon: "Gift",
		lifestyleType: "income",
	},
	{
		id: "21",
		name: "Other",
		type: "income",
		icon: "MoreHorizontal",
		lifestyleType: "none",
	},
	{
		id: "22",
		name: "Savings Interest",
		type: "income",
		icon: "PiggyBank",
		lifestyleType: "savings",
	},
	{
		id: "23",
		name: "Bank Interest",
		type: "income",
		icon: "PiggyBank",
		lifestyleType: "savings",
		mainCategoryId: "22",
	},
];
